# /// script
# dependencies = [
#     "altair==6.0.0",
#     "marimo",
#     "numpy==2.4.4",
#     "pandas==3.0.2",
#     "pyarrow==23.0.1",
# ]
# requires-python = ">=3.12"
# ///

import marimo

__generated_with = "0.22.0"
app = marimo.App(width="medium")


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""
    # Synthetic Entity Data — Exploratory Data Analysis

    This notebook explores the synthetic private-banking dataset generated by `main.py`.
    The dataset simulates advisor conduct risk, covering four bad-apple typologies:
    **Unsuitable Recommendations**, **Churning**, **Misrepresentation**, and **Liquidity Mismatch**.

    The goal of this EDA is to validate that the generation pipeline produces realistic and well-distributed data
    before it is used to train a conduct-risk ML classifier. Specifically, we inspect:

    - **Advisors** — typology distribution and bad-apple rate
    - **Clients** — age, risk tolerance, AUM, investment goal, and K&E flag distributions; age-dependent profile shifts
    - **Products** — risk rating, tenor, commission rate, and lockup distributions by product type
    """)
    return


@app.cell
def _():
    import marimo as mo
    import pandas as pd
    import altair as alt

    advisors = pd.read_csv("../output/advisors.csv")
    clients = pd.read_csv("../output/clients.csv")
    products = pd.read_csv("../output/products.csv")
    txn = pd.read_csv("../output/trade_suitability.csv")

    advisor_count = advisors.shape[0]
    client_count = clients.shape[0]
    product_count = products.shape[0]

    print(f"""
    Generated entities
    Number of advisor: {advisor_count}
    Number of client: {client_count}
    Number of products: {product_count}""")
    return advisors, alt, clients, mo, products


@app.cell(hide_code=True)
def _(advisors, alt, mo):
    advisors_chart = (
        alt.Chart(advisors)
        .mark_bar()
        .encode(
            x=alt.X(field='risk_typology', type='nominal'),
            y=alt.Y(aggregate='count', type='quantitative'),
            tooltip=[
                alt.Tooltip(field='risk_typology'),
                alt.Tooltip(aggregate='count')
            ]
        )
        .properties(
            title='Distribution of Advisor Typolgy',
            height=290,
            width='container',
            config={
                'axis': {
                    'grid': False
                }
            }
        )
    )

    advisor_description = mo.md(
        """
        ##**Exploring Advisor Data**
        <br> In this synthetic dataset, 90% of advisor is tagged  as "Clean" meaning his investment advises suitable to clients.
        <br> Other risk typologis are low in simulate realism.
        """
    )

    mo.vstack(
        [
            advisor_description,
            advisors_chart,
        ]
    )
    return


@app.cell(hide_code=True)
def _(alt, clients, mo):

    goal_order = ["capital preservation", "income", "growth", "speculation"]

    risk_profile_heatmap = (
        alt.Chart(clients)
        .mark_rect()
        .encode(
            x=alt.X(field='risk_tolerance', type='nominal', sort='ascending'),
            y=alt.Y(field='investment_goal', type='nominal', sort=goal_order[::-1]),
            color=alt.Color(aggregate='count', type='quantitative'),
            tooltip=[
                alt.Tooltip(field='risk_tolerance', format=',.0f'),
                alt.Tooltip(field='investment_goal'),
                alt.Tooltip(aggregate='count')
            ]
        )
        .properties(
            title="Client's goal and tolerance distribution",
            height=290,
            width='container',
            config={
                'axis': {
                    'grid': False
                }
            }
        )
    )

    c1 = mo.ui.altair_chart(risk_profile_heatmap)

    client_eda_description = mo.md(
        """
        ## **Exploring Client Data**
        <br> Client's investment goal and risk tolerance are criteria to determine risk appetite profile.
        <br> The following heatmap shows the client distribution of investment goal and risk tolerance.
        <br> Use the mouse the drag and select the groups of clients and the below dashboard will reflect.
        """
    )


    mo.vstack(
        [
            client_eda_description,
            c1
        ]
    )
    return c1, goal_order


@app.cell(hide_code=True)
def _(alt, c1, goal_order, mo):
    # 1. Define the Chart correctly
    _chart = (
        alt.Chart(c1.value)
        .mark_line(interpolate='monotone', strokeWidth=3)
        .encode(
            x=alt.X('age:Q', title='Age'),
            y=alt.Y('count()', title='Number of Clients'),
            tooltip=[
                alt.Tooltip('age:Q', format=',.0f'),
                alt.Tooltip('count()')
            ]
        )
        .properties(
            height=290,
            width=900
        )
        # Use dedicated configuration methods instead of the 'config' dict
        .configure_axis(grid=False)
        .configure_view(stroke=None) 
    )

    chart_age_risk_tolerance = alt.Chart(c1.value).mark_boxplot().encode(
        x=alt.X('age:Q', title='Client Age vs Risk Tolerance'),
        y=alt.Y('risk_tolerance:O', title='', sort='descending')
    ).properties(width=220)

    chart_age_investment_goal = alt.Chart(c1.value).mark_boxplot().encode(
        x=alt.X('age:Q', title='Client Age vs Investment Goal'),
        y=alt.Y('investment_goal:O', title='', sort=goal_order[::-1])
    ).properties(width=220)

    chart_age_liquidity_needs = alt.Chart(c1.value).mark_boxplot().encode(
        x=alt.X('age:Q', title='Client Age vs Liquidity Needs'),
        y=alt.Y('liquidity_needs:O', title='', sort=['high', 'medium', 'low'])
    ).properties(width=220)


    def mark_ke_dount(dataf, prod, scale = 1):

        try:
            percentage = c1.value[prod].sum() / c1.value[prod].count()
        except:
            percentage = 0

        # Donut Layer
        donut = alt.Chart(c1.value).mark_arc(innerRadius=60 * scale, outerRadius=100 * scale).encode(
                color=alt.Color(field=prod, type='nominal', legend=None),
                theta=alt.Theta(aggregate='count', type='quantitative')
        )

        t = alt.Chart(c1.value).mark_text(
            baseline='middle',
            fontSize=18 * scale,
            fontWeight='normal',  # <--- This unbolds the text
            color='black').encode(text=alt.value(f"{percentage:.1%}"))

        return (donut + t).properties(title=prod, width=150* scale, height=150* scale)

    ke_charts = mark_ke_dount(c1, 'ke_equities', scale=0.8) | mark_ke_dount(c1, 'ke_fixed_income', scale=0.8) | mark_ke_dount(c1, 'ke_structured_prods', scale=0.8) | mark_ke_dount(c1, 'ke_derivatives', scale=0.8) | mark_ke_dount(c1, 'ke_alternatives', scale=0.8)

    # Helper to safely get unique values or an empty string if empty
    def get_unique_values(series):
        if series.empty:
            return "N/A"
        return ", ".join([str(v) for v in sorted(series.unique())])

    # Safely get aggregated values
    if c1.value is not None and not c1.value.empty:
        num_clients = len(c1.value)
        total_aum = c1.value.aum_usd.sum()
        mean_age = c1.value.age.mean()
        std_age = c1.value.age.std()
        selected_goals = get_unique_values(c1.value.investment_goal)
        selected_risk_tol = get_unique_values(c1.value.risk_tolerance)
    else:
        num_clients = 0
        total_aum = 0
        mean_age = 0
        std_age = 0
        selected_goals = "N/A"
        selected_risk_tol = "N/A"

    client_summary = mo.md(f"""
    | Metric                 | Value                                                              |
    | :--------------------- | :----------------------------------------------------------------- |
    | **Number of Clients**  | {num_clients}                                                      |
    | **AUM (USD)**          | {total_aum / 100_000_000:0.2f}M                                     |
    | **Age Mean**           | {mean_age:.2f}                                                     |
    | **Age SD**             | {std_age:.2f}                                                      |
    | **Selected Goals**     | {selected_goals}                                                   |
    | **Selected Risk Tol.** | {selected_risk_tol}                                                |
    """)


    # 2. Display using hstack
    # Ensure this is the LAST line of the cell or assigned to a variable displayed by marimo
    mo.vstack(
        [
            client_summary,
            _chart,
        ]
    )
    return (
        chart_age_investment_goal,
        chart_age_liquidity_needs,
        chart_age_risk_tolerance,
        ke_charts,
    )


@app.cell(hide_code=True)
def _(
    chart_age_investment_goal,
    chart_age_liquidity_needs,
    chart_age_risk_tolerance,
    ke_charts,
    mo,
):
    mo.vstack(
        [
            chart_age_investment_goal | chart_age_risk_tolerance | chart_age_liquidity_needs,
            ke_charts
        ]
    )
    return


@app.cell(hide_code=True)
def _(mo):
    mo.md("""
    **A note on client generation design choices:**

    | Field             | Distribution                                                                                   |
    | :---------------- | :--------------------------------------------------------------------------------------------- |
    | age               | Fat-tailed t-dist (df=4, centre=50, scale=12), rejection-sampled to avoid boundary pile-up     |
    | risk_tolerance    | Discrete weighted choice (1–5) from cfg.risk_tolerance_distribution                              |
    | aum_usd           | Log-normal (exp(Normal(12, 1))), then min-max scaled to configured range                        |
    | liquidity_needs   | Discrete weighted choice from cfg.liquidity_needs_distribution                                   |
    | investment_goal   | Base config weights, age-adjusted: older clients get boosted capital preservation/income, reduced growth |
    | ke_* flags        | Independent Bernoulli per product type, probabilities from cfg.ke_probability                    |


    Two age-dependency layers add realism:
    <br> - Risk tolerance cap — hard ceilings by age bracket (e.g. age >80 → max RT=1), with age_risk_epsilon exception rate
    <br> - Investment goal bias — smooth linear shift starting at age 40 via age_factor = clip((age-40)/40, 0, 1)
    """)
    return


@app.cell(hide_code=True)
def _(alt, mo, products):
    product_type_boxplot_risk = alt.Chart(products).mark_boxplot().encode(
        y=alt.X('product_type', title='Product Type'), # Transposed
        x=alt.Y('actual_risk_rating', title='Actual Risk Rating'), # Transposed
        tooltip=['product_type', 'actual_risk_rating']
    ).properties(title='Actual Risk Rating Distribution by Product Type')

    product_type_boxplot_tenor = alt.Chart(products).mark_boxplot().encode(
        y=alt.X('product_type', title='Product Type'), # Transposed
        x=alt.Y('recommended_tenor_yrs', title='Recommended Tenor (Years)'), # Transposed
        tooltip=['product_type', 'recommended_tenor_yrs']
    ).properties(title='Recommended Tenor by Product Type')

    product_type_boxplot_commission = alt.Chart(products).mark_boxplot().encode(
        y=alt.X('product_type', title='Product Type'), # Transposed
        x=alt.Y('commission_rate', title='Commission Rate'), # Transposed
        tooltip=['product_type', 'commission_rate']
    ).properties(title='Commission Rate Distribution by Product Type')

    product_type_boxplot_lockup = alt.Chart(products).mark_boxplot().encode(
        y=alt.X('product_type', title='Product Type'), # Transposed
        x=alt.Y('lockup_days', title='Lockup Days'), # Transposed
        tooltip=['product_type', 'lockup_days']
    ).properties(title='Lockup Days Distribution by Product Type')

    product_description = mo.md(
        """
        ##**Exploring Product Data**
        """
    )



    mo.vstack([
        product_description,
        product_type_boxplot_risk|product_type_boxplot_tenor,
        product_type_boxplot_commission|product_type_boxplot_lockup,
    ])
    return


if __name__ == "__main__":
    app.run()
